"""
Django settings for service_site project.

Generated by 'django-admin startproject' using Django 6.0.2.

https://docs.djangoproject.com/en/6.0/topics/settings/

https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# ==========================================================
# BASE DIRECTORY
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================================
# SECURITY
# ==========================================================

SECRET_KEY = "django-insecure-vw_1*bg*0lu%mb690(=+n$rv3h^gq@*+3mep87xo$ixrik(y(e"

DEBUG = True

ALLOWED_HOSTS = [

    "127.0.0.1",

    "localhost",

    "amir1384.pythonanywhere.com",

]

# ==========================================================
# PROJECT INFORMATION
# ==========================================================

PROJECT_NAME = "Nexora Web"

PROJECT_VERSION = "1.0.0"

PROJECT_COMPANY = "Nexora Holding"

PROJECT_DESCRIPTION = (
    "Professional Website Design & Development"
)

PROJECT_EMAIL = "info@nexora.ir"

PROJECT_PHONE = "+98 900 000 0000"

PROJECT_WEBSITE = "https://nexora.ir"

# ==========================================================
# APPLICATIONS
# ==========================================================

INSTALLED_APPS = [

    "jazzmin",

    "django.contrib.admin",

    "django.contrib.auth",

    "django.contrib.contenttypes",

    "django.contrib.sessions",

    "django.contrib.messages",

    "django.contrib.staticfiles",

    # Local Apps

    "core",

    "accounts",

]

# ==========================================================
# MIDDLEWARE
# ==========================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.locale.LocaleMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]

# ==========================================================
# URLS
# ==========================================================

ROOT_URLCONF = "service_site.urls"

WSGI_APPLICATION = "service_site.wsgi.application"

# ==========================================================
# TEMPLATES
# ==========================================================

TEMPLATES = [

    {

        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [

            BASE_DIR / "templates",

        ],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.debug",

                "django.template.context_processors.request",

                "django.template.context_processors.i18n",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

                "core.context_processors.global_data",

            ],

        },

    },

]

# ==========================================================
# DATABASE
# ==========================================================

DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.sqlite3",

        "NAME": BASE_DIR / "db.sqlite3",

    }

}

# ==========================================================
# PASSWORD VALIDATION
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]

# ==========================================================
# INTERNATIONALIZATION
# ==========================================================

LANGUAGE_CODE = "fa"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [

    ("fa", "فارسی"),

    ("en", "English"),

]

LOCALE_PATHS = [

    BASE_DIR / "locale",

]

FORMAT_MODULE_PATH = [

    "locale",

]

# ==========================================================
# LOGIN SETTINGS
# ==========================================================

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "dashboard"

LOGOUT_REDIRECT_URL = "home"

# ==========================================================
# SESSION
# ==========================================================

SESSION_ENGINE = "django.contrib.sessions.backends.db"

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30

SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_COOKIE_HTTPONLY = True

SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_HTTPONLY = True

CSRF_COOKIE_SAMESITE = "Lax"

# ==========================================================
# STATIC FILES
# ==========================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [

    BASE_DIR / "static",

]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_FINDERS = [

    "django.contrib.staticfiles.finders.FileSystemFinder",

    "django.contrib.staticfiles.finders.AppDirectoriesFinder",

]

# ==========================================================
# MEDIA FILES
# ==========================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024

FILE_UPLOAD_PERMISSIONS = 0o644

# ==========================================================
# DEFAULT AUTO FIELD
# ==========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==========================================================
# MESSAGE STORAGE
# ==========================================================

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

# ==========================================================
# CACHE
# ==========================================================

CACHES = {

    "default": {

        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",

        "LOCATION": "nexora-web-cache",

    }

}

# ==========================================================
# COMPANY
# ==========================================================

COMPANY_NAME = "Nexora Web"

COMPANY_EMAIL = "info@nexora.ir"

COMPANY_PHONE = "+98 900 000 0000"

COMPANY_WEBSITE = "https://nexora.ir"

COMPANY_ADDRESS = "Iran"

# ==========================================================
# JAZZMIN SETTINGS
# ==========================================================

JAZZMIN_SETTINGS = {

    "site_title": "Nexora Web Admin",

    "site_header": "Nexora Web",

    "site_brand": "Nexora Web",

    "site_logo": "img/logo-web.png",

    "login_logo": "img/logo-web.png",

    "login_logo_dark": "img/logo-web.png",

    "site_icon": "img/logo-web.png",

    "welcome_sign": "Welcome to Nexora Web Administration",

    "copyright": "Nexora Holding",

    "search_model": [

        "core.Service",

        "core.Portfolio",

        "core.Order",

        "accounts.User",

    ],

    "topmenu_links": [

        {

            "name": "Website",

            "url": "/",

            "new_window": True,

        },

    ],

    "show_sidebar": True,

    "navigation_expanded": True,

    "hide_apps": [],

    "hide_models": [],

    "order_with_respect_to": [

        "core",

        "accounts",

        "auth",

    ],

    "icons": {

        "auth": "fas fa-users-cog",

        "auth.user": "fas fa-user",

        "auth.Group": "fas fa-users",

        "core.Service": "fas fa-code",

        "core.Portfolio": "fas fa-laptop-code",

        "core.Order": "fas fa-shopping-cart",

    },

    "custom_css": "css/style.css",

    "language_chooser": True,

    "changeform_format": "horizontal_tabs",

    "theme": "darkly",

    "dark_mode_theme": "darkly",

    "show_ui_builder": True,

}

# ==========================================================
# SECURITY
# ==========================================================

SECURE_CONTENT_TYPE_NOSNIFF = True

SECURE_BROWSER_XSS_FILTER = True

X_FRAME_OPTIONS = "DENY"

CSRF_COOKIE_SECURE = False

SESSION_COOKIE_SECURE = False

CSRF_COOKIE_HTTPONLY = True

SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_SAMESITE = "Lax"

SECURE_REFERRER_POLICY = "same-origin"

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

APPEND_SLASH = True

# ==========================================================
# EMAIL
# ==========================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_USE_SSL = False

EMAIL_HOST_USER = ""

EMAIL_HOST_PASSWORD = ""

DEFAULT_FROM_EMAIL = "Nexora Web <noreply@nexora.ir>"

SERVER_EMAIL = DEFAULT_FROM_EMAIL

# ==========================================================
# ORDER SETTINGS
# ==========================================================

ORDER_PREFIX = "NW"

INVOICE_PREFIX = "INV"

TRACKING_PREFIX = "TR"

TRACKING_CODE_LENGTH = 10

DEFAULT_CURRENCY = "IRT"

# ==========================================================
# FILE SETTINGS
# ==========================================================

IMAGE_MAX_SIZE = 10 * 1024 * 1024

ALLOWED_IMAGE_EXTENSIONS = [

    ".jpg",

    ".jpeg",

    ".png",

    ".webp",

    ".svg",

]

# ==========================================================
# SEO
# ==========================================================

SITE_NAME = "Nexora Web"

SITE_TITLE = "Nexora Web"

SITE_TAGLINE = "Professional Website Design"

SITE_DESCRIPTION = (
    "Professional Website Design, "
    "Online Stores, "
    "Web Applications and UI/UX."
)

SITE_KEYWORDS = [

    "Website Design",

    "Web Development",

    "Online Shop",

    "Web Application",

    "UI",

    "UX",

    "Nexora Web",

]

SITE_URL = "https://nexora.ir"

# ==========================================================
# SOCIAL LINKS
# ==========================================================

SOCIAL_LINKS = {

    "telegram": "https://t.me/nexora",

    "instagram": "https://instagram.com/nexora",

    "linkedin": "https://linkedin.com/company/nexora",

    "github": "https://github.com/nexora",

}

# ==========================================================
# DEFAULT FILES
# ==========================================================

DEFAULT_LOGO = "img/logo-web.png"

DEFAULT_FAVICON = "img/logo-web.png"

DEFAULT_OG_IMAGE = "img/logo-web.png"

# ==========================================================
# FEATURES
# ==========================================================

ENABLE_TRACKING = True

ENABLE_CONTACT = True

ENABLE_ORDER = True

ENABLE_PORTFOLIO = True

ENABLE_CAREERS = True

ENABLE_DASHBOARD = True

ENABLE_PROFILE = True

ENABLE_BLOG = False

# ==========================================================
# UI
# ==========================================================

PRIMARY_COLOR = "#dc3545"

SECONDARY_COLOR = "#991b1b"

DEFAULT_THEME = "dark"

FONT_FAMILY = "Vazirmatn"

BORDER_RADIUS = "18px"

ENABLE_LANGUAGE_SWITCH = True

# ==========================================================
# LOGGING
# ==========================================================

LOGGING = {

    "version": 1,

    "disable_existing_loggers": False,

    "formatters": {

        "standard": {

            "format": "[{levelname}] {asctime} {name}: {message}",

            "style": "{",

        },

    },

    "handlers": {

        "console": {

            "class": "logging.StreamHandler",

            "formatter": "standard",

        },

    },

    "root": {

        "handlers": ["console"],

        "level": "INFO",

    },

}

# ==========================================================
# DEVELOPMENT
# ==========================================================

INTERNAL_IPS = [

    "127.0.0.1",

]

# ==========================================================
# BRAND INFORMATION
# ==========================================================

BRAND = {

    "name": "Nexora Web",

    "company": "Nexora Holding",

    "version": PROJECT_VERSION,

    "logo": DEFAULT_LOGO,

    "favicon": DEFAULT_FAVICON,

    "description": SITE_DESCRIPTION,

    "website": SITE_URL,

    "email": COMPANY_EMAIL,

    "phone": COMPANY_PHONE,

}

# ==========================================================
# MODULES
# ==========================================================

ENABLED_MODULES = {

    "services": True,

    "portfolio": True,

    "orders": True,

    "tracking": True,

    "accounts": True,

    "dashboard": True,

    "careers": True,

    "contact": True,

    "language_switch": True,

}

# ==========================================================
# CUSTOM SETTINGS
# ==========================================================

NEXORA = {

    "company_name": "Nexora Web",

    "holding_name": "Nexora Holding",

    "default_language": "fa",

    "default_theme": "dark",

    "maintenance_mode": False,

}

# ==========================================================
# END OF FILE
# ==========================================================