# Generated by Django 6.0.2 on 2026-06-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام خدمت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('base_price', models.IntegerField(verbose_name='قیمت پایه (تومان)')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون Font Awesome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='عکس پروژه')),
                ('link', models.URLField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('estimated_price', models.IntegerField(verbose_name='قیمت تخمینی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('processing', 'در حال انجام'), ('completed', 'تحویل داده شد')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='نوع خدمت')),
            ],
        ),
    ]
