# Generated by Django 6.0.2 on 2026-07-07 23:19

import core.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ فعالیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='نام دپارتمان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('hire_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('successful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تاریخچه ورود',
                'verbose_name_plural': 'تاریخچه ورود',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='عملیات')),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تاریخچه سفارش',
                'verbose_name_plural': 'تاریخچه سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('private', models.BooleanField(default=True, verbose_name='خصوصی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'یادداشت سفارش',
                'verbose_name_plural': 'یادداشت\u200cهای سفارش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'همکار',
                'verbose_name_plural': 'همکاران',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('authority', models.CharField(blank=True, max_length=120)),
                ('ref_id', models.CharField(blank=True, max_length=120)),
                ('gateway', models.CharField(default='Zarinpal', max_length=50)),
                ('successful', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['sort_order'],
            },
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'فرصت شغلی', 'verbose_name_plural': 'فرصت\u200cهای شغلی'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام تماس', 'verbose_name_plural': 'پیام\u200cهای تماس'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'قرارداد', 'verbose_name_plural': 'قراردادها'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست همکاری', 'verbose_name_plural': 'درخواست\u200cهای همکاری'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کارها'},
        ),
        migrations.AlterModelOptions(
            name='projectprogress',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیشرفت پروژه', 'verbose_name_plural': 'پیشرفت پروژه'},
        ),
        migrations.AlterModelOptions(
            name='projecttask',
            options={'ordering': ['deadline', '-created_at'], 'verbose_name': 'وظیفه', 'verbose_name_plural': 'وظایف پروژه'},
        ),
        migrations.AlterModelOptions(
            name='projecttimeline',
            options={'ordering': ['event_date'], 'verbose_name': 'تایم لاین', 'verbose_name_plural': 'تایم لاین پروژه'},
        ),
        migrations.AlterModelOptions(
            name='projectversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'نسخه پروژه', 'verbose_name_plural': 'نسخه\u200cهای پروژه'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'سرویس', 'verbose_name_plural': 'سرویس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['created_at'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربران'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='body',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='position',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
        migrations.RemoveField(
            model_name='projectprogress',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectprogress',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projecttimeline',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='career',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='مزایا'),
        ),
        migrations.AddField(
            model_name='career',
            name='experience',
            field=models.CharField(blank=True, max_length=100, verbose_name='سابقه مورد نیاز'),
        ),
        migrations.AddField(
            model_name='career',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AddField(
            model_name='career',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='محل کار'),
        ),
        migrations.AddField(
            model_name='career',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='وظایف'),
        ),
        migrations.AddField(
            model_name='career',
            name='short_description',
            field=models.CharField(default='', max_length=250, verbose_name='توضیح کوتاه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='temporary-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='career',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='career',
            name='vacancies',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد ظرفیت'),
        ),
        migrations.AddField(
            model_name='career',
            name='work_type',
            field=models.CharField(default='Remote', max_length=80, verbose_name='نوع همکاری'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=150, verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(db_index=True, default='Unknown', max_length=150, verbose_name='نام کامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='contract',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, default='INV-OLD-000001', max_length=30, unique=True, verbose_name='شماره فاکتور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.PositiveIntegerField(default=0, verbose_name='مالیات'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='career',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.career'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='یادداشت مدیریت'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_seen',
            field=models.BooleanField(default=False, verbose_name='مشاهده توسط مشتری'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='زمان تقریبی اجرا'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه نهایی'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(db_index=True, default='Unknown', max_length=150, verbose_name='نام کامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_portfolio, verbose_name='تصویر دوم'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='لینک GitHub'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(blank=True, verbose_name='آدرس پروژه'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='short_description',
            field=models.CharField(default='', max_length=250, verbose_name='توضیح کوتاه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecttimeline',
            name='event_date',
            field=models.DateTimeField(default=datetime.date(2026, 7, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نمایش عمومی'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='مدت تقریبی اجرا (روز)'),
        ),
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='سرویس ویژه'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر سرویس'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(default='', max_length=250, verbose_name='توضیح کوتاه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False, verbose_name='پیام مدیریت'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(verbose_name='شرح کامل'),
        ),
        migrations.AlterField(
            model_name='career',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='شرایط استخدام'),
        ),
        migrations.AlterField(
            model_name='career',
            name='salary',
            field=models.CharField(blank=True, max_length=120, verbose_name='حقوق'),
        ),
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='عنوان شغل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('cancelled', 'باطل شده')], db_index=True, default='unpaid', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to=core.models.upload_to_resumes, validators=[core.models.validate_file_size, django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to_orders, validators=[core.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'zip', 'rar', 'png', 'jpg', 'jpeg', 'fig', 'xd', 'psd'])], verbose_name='فایل پیوست'),
        ),
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.PositiveBigIntegerField(default=0, verbose_name='بودجه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='ددلاین'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(verbose_name='توضیحات پروژه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه تقریبی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.service', verbose_name='سرویس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال انجام'), ('review', 'در انتظار تایید'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(db_index=True, default='OLD-TRACK-000001', editable=False, max_length=20, unique=True, verbose_name='کد رهگیری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='website',
            field=models.URLField(blank=True, verbose_name='وب سایت'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='پروژه ویژه'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_to_portfolio, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='core.service', verbose_name='سرویس'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technologies',
            field=models.CharField(blank=True, help_text='Python, Django, React, Bootstrap ...', max_length=300, verbose_name='تکنولوژی\u200cها'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(db_index=True, max_length=180, verbose_name='عنوان پروژه'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('todo', 'انجام نشده'), ('doing', 'در حال انجام'), ('done', 'انجام شده')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='file',
            field=models.FileField(upload_to=core.models.upload_to_versions, validators=[core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='version',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='مثال: fas fa-code', max_length=100, verbose_name='آیکون FontAwesome'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=170, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='عنوان سرویس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to_tickets, validators=[core.models.validate_file_size, django.core.validators.FileExtensionValidator(['pdf', 'zip', 'rar', 'png', 'jpg', 'jpeg', 'doc', 'docx'])], verbose_name='فایل پیوست'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['created_at'], name='core_contac_created_643cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_read'], name='core_contac_is_read_712816_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='core_notifi_is_read_127eae_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='notification_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_code'], name='core_order_trackin_9d9a59_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='core_order_status_6fe5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='core_order_created_912d27_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='core_order_user_id_f84106_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_code'], name='order_tracking_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='order_user_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['slug'], name='core_portfo_slug_f811fa_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['featured'], name='core_portfo_feature_c0536b_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['active'], name='core_portfo_active_4e8d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['created_at'], name='core_portfo_created_2d66e8_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['active'], name='core_servic_active_b74acc_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['featured'], name='core_servic_feature_b52e18_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='core_servic_slug_521ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='core_ticket_created_fe6f19_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_read'], name='core_ticket_is_read_812e92_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_admin'], name='core_ticket_is_admi_bb8893_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order'], name='ticket_order_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sender'], name='ticket_sender_idx'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.order'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice'),
        ),
    ]
